"""create projects table

Revision ID: 66e0e2087e0d
Revises: 
Create Date: 2026-04-28 07:49:39.149734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e0e2087e0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('sector_pack', sa.String(length=64), nullable=False),
    sa.Column('perimeter', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('accounting_standard', sa.String(length=16), nullable=False),
    sa.Column('horizon_years', sa.Integer(), nullable=False),
    sa.Column('tier_level', sa.String(length=32), nullable=True),
    sa.Column('etr_default', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_name'))
        batch_op.drop_index(batch_op.f('ix_projects_deleted_at'))

    op.drop_table('projects')
    # ### end Alembic commands ###
